name: Deploy to AWS

on:
  push:
    branches: [ master, amazon-web-services ]
  pull_request:
    branches: [ master, amazon-web-services ]

jobs:
  push:
    name: Push docker image to Github Container Registry (GHCR)
    runs-on: ubuntu-latest
    steps:
      - id: prep
        run: |
          REGISTRY=ghcr.io
          SUBJECT=amazon-web-services
          echo ::set-output name=registry::${REGISTRY}
          echo ::set-output name=context::./public/${SUBJECT}
          echo ::set-output name=tags::${REGISTRY}/${GITHUB_REPOSITORY}:${SUBJECT}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Fix symlinked files
        env:
          CONTEXT: ${{ steps.prep.outputs.context }}
        run: |
          rm -v ${CONTEXT}/Dockerfile
          cp -fv ./public/Dockerfile ${CONTEXT}
          rm -v ${CONTEXT}/style.css
          cp -fv ./public/style.css ${CONTEXT}

      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          registry: ${{ steps.prep.outputs.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          context: ${{ steps.prep.outputs.context }}
          file: ./public/Dockerfile
