name: Deploy to AWS

on:
  push:
    branches: [ master, amazon-web-services ]
  pull_request:
    branches: [ master, amazon-web-services ]

jobs:
  push:
    name: Push docker image to Github Container Registry (GHCR)
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the variables
        id: prep
        run: |
          echo ::set-output name=website::amazon-web-services
          echo ::set-output name=registry::ghcr.io
          echo ::set-output name=context::./dist
          echo ::set-output name=tags::${REGISTRY}/${GITHUB_REPOSITORY}:${SUBJECT}

      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Build the app for production
        env:
          CONTEXT: ${{ steps.prep.outputs.context }}
          WEBSITE: ${{ steps.prep.outputs.website }}
        run: |
          mkdir -p ${CONTEXT}
          cp -fv ./websites/${WEBSITE}/* ${CONTEXT}

      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          registry: ${{ steps.prep.outputs.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          context: ${{ steps.prep.outputs.context }}
          file: ${{ steps.prep.outputs.context }}/Dockerfile
